### PR TITLE
Update step04.md

### PR DESCRIPTION
**Pull request by mario-guerra**
Lightly edited for clarity.

### CODE REVIEW

**Review by timotheeguerin — APPROVED** [review]

**Comment by mario-guerra** [comment]
@markcowl I have the microsoft/typespec submodule cloned locally and I've installed 'typespec/prettier-plugin-typespec' in addition to the Prettier extension, but I'm getting errors from Prettier due to missing deps. Do we have guidance on the proper way to set this up?

["INFO" - 3:41:01 PM] Formatting file:///c%3A/Users/marioguerra/Work/typespec-azure/docs/getstarted/azure-core/step04.md
["ERROR" - 3:41:01 PM] Error resolving prettier configuration for c:\Users\marioguerra\Work\typespec-azure\docs\getstarted\azure-core\step04.md
["ERROR" - 3:41:01 PM] Error loading node module 'c:\Users\marioguerra\Work\typespec-azure\core\packages\compiler\node_modules\prettier\index.cjs'
Error: Error loading node module 'c:\Users\marioguerra\Work\typespec-azure\core\packages\compiler\node_modules\prettier\index.cjs'

**Comment by timotheeguerin** [comment]
Did you follow the instruction to install dependencies in the repo https://github.com/Azure/typespec-azure/blob/main/CONTRIBUTING.md?

`pnpm install`, `pnpm build`, `pnpm format`

**Comment by mario-guerra** [comment]
Thanks @timotheeguerin, I was able to run the formatter but there is no change to the file for me to check in after formatting. What is the failing check looking for?

**Comment by mario-guerra** [comment]
I'm going to redo this PR following the guidance, closing this one.

**Comment by timotheeguerin** [comment]
It should have updated the file, it's weird it didn't. Formatting it in Vscode with prettier extension also should work

**Pull request closed without merging**
